services:
  influxdb2:
    image: influxdb:latest
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: AdminToken0==
      DOCKER_INFLUXDB_INIT_ORG: solar-charge
      DOCKER_INFLUXDB_INIT_BUCKET: home
      DOCKER_INFLUXDB_INIT_RETENTION: 2d
    volumes:
      - influxdb2-data:/var/lib/influxdb2

  solar-charge:
    build:
      context: ./SolarCharge.API
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      Serilog__MinimumLevel__Default: "Verbose"
      Features__IsInfluxEnabled: true
      Inverter__Type: "Fronius"
      Inverter__Url: "http://192.168.1.51"
      InfluxDb__Url: http://influxdb2:8086
      InfluxDb__Token: AdminToken0==
      Application__InverterStatusCheckCron: "*/2 * * * *"
      Application__EvaluateSolarGenerationCron": "*/10 * * * *"
      Persistence__ConnectionString: "Data Source=/persistence/app.db"
    volumes:
      - app-data:/persistence/app.db
    depends_on:
      - influxdb2
  
  solar-charge-telegram:
    build:
      context: ./SolarCharge.ChatBot
      dockerfile: Dockerfile
    environment:
      Serilog__MinimumLevel__Default: "Verbose"
      Persistence__ConnectionString: "Data Source=/persistence/chatbot.db"
      Telegram__BotToken: "YOUR_TELEGRAM_BOT_TOKEN"
    ports:
      - 5010:5010
    volumes:
      - telegram-data:/persistence/chatbot.db

volumes:
  influxdb2-data:
  app-data:
  telegram-data: