
name: Create and publish Docker images

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Build and push SolarCharge.API
      - name: Extract metadata (tags, labels) for SolarCharge.API
        id: meta-api
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build and push SolarCharge.API Docker image 
        id: push-api
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./src/SolarCharge.API
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-api.outputs.tags }}
          labels: ${{ steps.meta-api.outputs.labels }}
      
      # Build and push SolarCharge.ChatBot
      - name: Extract metadata (tags, labels) for SolarCharge.ChatBot
        id: meta-chatbot
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-chatbot
          tags: |
            type=ref,event=tag
            type=raw,value=latest,enable={{is_default_branch}}
      
      - name: Build and push SolarCharge.ChatBot Docker image
        id: push-chatbot
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ./src/SolarCharge.ChatBot
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-chatbot.outputs.tags }}
          labels: ${{ steps.meta-chatbot.outputs.labels }}
      
      # This step generates an artifact attestation for the images, which is an unforgeable statement about where and how they were built. It increases supply chain security for people who consume the images. For more information, see [Using artifact attestations to establish provenance for builds](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds).
      # These steps will remain commented out until the repository is public
      # - name: Generate artifact attestation for API
      #   uses: actions/attest-build-provenance@v2
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}-api
      #     subject-digest: ${{ steps.push-api.outputs.digest }}
      #     push-to-registry: true
      
      # - name: Generate artifact attestation for ChatBot
      #   uses: actions/attest-build-provenance@v2
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}-chatbot
      #     subject-digest: ${{ steps.push-chatbot.outputs.digest }}
      #     push-to-registry: true